module.exports = {
    purge: [],
    theme: {
        extend: {},
        textColor: {
            pscolor: "#192a93",
            white: "#FFFFFF",
            pslite: "#2f41b7",
        },
        backgroundColor: (theme) => ({
            ...theme("colors"),
            pscolor: "#192a93",
            pslite: "#2f41b7",
        }),
        fontSize: {
            xs: ".75rem",
            sm: ".875rem",
            h1: "1.3rem",
            h2: "1.2rem",
            h3: "0.95rem",
            base: "1rem",
            lg: "1.125rem",
            xl: "1.25rem",
            "2xl": "1.5rem",
            "3xl": "1.875rem",
            "4xl": "2.25rem",
            "5xl": "3rem",
            "6xl": "4rem",
            "7xl": "5rem",
        },
        fontFamily: {
            sans: ["-apple-system", "BlinkMacSystemFont"],
            serif: ["Georgia", "Cambria"],
            mono: ["SFMono-Regular", "Menlo"],
            display: ["Oswald"],
            body: ["Open Sans"],
            blog: "ABeeZee,Helvetica,Arial,Lucida,sans-serif",
        },
        borderColor: (theme) => ({
            ...theme("colors"),
            default: theme("colors.gray.300", "currentColor"),
            grey: "#dfe8f4",
            secondary: "#ffed4a",
            danger: "#e3342f",
            pscolor: "#192a93",
            pslite: "#2f41b7",
        }),
        maxWidth: {
            icon: "8rem",
        },
    },
    variants: { backgroundColor: ["responsive", "hover", "focus", "active"] },
    plugins: [],
};